services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
        - 27017:27017
    volumes:
        - mongo-data:/data/db

  ecomerce:
    image: sustentacaoecommerce:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/admin
    depends_on:
      - mongo


volumes:
    mongo-data:
        driver: local

networks:
  default:
    name: sustentacaoEcommerce-network
    driver: bridge