spring:
  application:
    name: sustentacaoEcommerce
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/admin

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: 'health,metrics,loggers,prometheus'
  endpoint:
    health:
      show-details: always

hybris:
  api:
    url: http://localhost:8080/mock/sap-hybris
